name: Pull Request Validation
on: [pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all branches
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch -a
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Nx globally
        run: npm install -g nx
      - name: Run all tests
        run: npx nx run-many --target=test --all --parallel=4
      - name: Run linting
        run: npx nx run-many --target=lint --all
      - name: Run Cypress tests
        run: npx nx run showcase:cy:run